import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router, ActivatedRoute } from '@angular/router';
import { ReactiveFormsModule, FormBuilder, FormGroup, FormArray, Validators } from '@angular/forms';
import { LocalizationModule } from '@abp/ng.core';
import { finalize } from 'rxjs';
import { DualCalendarPickerComponent, DualDate } from '../../shared/dual-calendar-picker.component';
import {
  InvoiceService,
  ZatcaInvoiceType,
  InvoiceTypeLabels,
} from '../services/invoice.service';
import { SellerService, ZatcaSellerDto } from '../services/seller.service';

@Component({
  selector: 'app-invoice-form',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    ReactiveFormsModule,
    LocalizationModule,
    DualCalendarPickerComponent,
  ],
  template: `
    <div class="card">
      <div class="card-header">
        <div class="row">
          <div class="col">
            <h5 class="card-title">
              {{ isEditMode ? ('::Saudi:Zatca:EditInvoice' | abpLocalization) : ('::Saudi:Zatca:CreateInvoice' | abpLocalization) }}
            </h5>
          </div>
        </div>
      </div>

      <div class="card-body">
        <!-- Loading -->
        <div *ngIf="loadingSellers" class="text-center py-4">
          <div class="spinner-border text-primary" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
        </div>

        <form *ngIf="!loadingSellers" [formGroup]="invoiceForm" (ngSubmit)="onSubmit()">
          <!-- Header Section -->
          <div class="row mb-3">
            <div class="col-md-6">
              <label class="form-label">
                {{ '::Saudi:Zatca:Seller' | abpLocalization }}
                <span class="text-danger">*</span>
              </label>
              <select class="form-select" formControlName="sellerId">
                <option value="">{{ '::Saudi:Zatca:SelectSeller' | abpLocalization }}</option>
                <option *ngFor="let seller of sellers" [value]="seller.id">
                  {{ seller.sellerNameEn || '' }} - {{ seller.sellerNameAr }}
                </option>
              </select>
              <div
                class="text-danger mt-1"
                *ngIf="invoiceForm.get('sellerId')?.invalid && invoiceForm.get('sellerId')?.touched"
              >
                {{ '::Saudi:Zatca:SellerRequired' | abpLocalization }}
              </div>
            </div>

            <div class="col-md-6">
              <label class="form-label">
                {{ '::Saudi:Zatca:InvoiceType' | abpLocalization }}
                <span class="text-danger">*</span>
              </label>
              <select class="form-select" formControlName="invoiceType">
                <option value="">{{ '::Saudi:Zatca:SelectType' | abpLocalization }}</option>
                <option *ngFor="let t of typeOptions" [value]="t.value">
                  {{ '::Saudi:Zatca:' + t.label | abpLocalization }}
                </option>
              </select>
              <div
                class="text-danger mt-1"
                *ngIf="invoiceForm.get('invoiceType')?.invalid && invoiceForm.get('invoiceType')?.touched"
              >
                {{ '::Saudi:Zatca:TypeRequired' | abpLocalization }}
              </div>
            </div>
          </div>

          <div class="row mb-3">
            <div class="col-md-6">
              <label class="form-label">
                {{ '::Saudi:Zatca:IssueDate' | abpLocalization }}
                <span class="text-danger">*</span>
              </label>
              <app-dual-calendar-picker
                [selectedDate]="issueDate"
                [gregorianLabel]="'::Saudi:Zatca:GregorianDate' | abpLocalization"
                [hijriLabel]="'::Saudi:Zatca:HijriDate' | abpLocalization"
                (dateChange)="onIssueDateChange($event)"
              />
            </div>

            <div class="col-md-6">
              <label class="form-label">
                {{ '::Saudi:Zatca:InvoiceNumber' | abpLocalization }}
              </label>
              <input type="text" class="form-control" formControlName="invoiceNumber" />
              <small class="text-muted">
                {{ '::Saudi:Zatca:AutoGeneratedIfEmpty' | abpLocalization }}
              </small>
            </div>
          </div>

          <!-- Buyer Information -->
          <h6 class="mb-3 mt-4">{{ '::Saudi:Zatca:BuyerInformation' | abpLocalization }}</h6>
          <div class="row mb-3">
            <div class="col-md-6">
              <label class="form-label">
                {{ '::Saudi:Zatca:BuyerName' | abpLocalization }}
                <span class="text-danger">*</span>
              </label>
              <input type="text" class="form-control" formControlName="buyerName" />
              <div
                class="text-danger mt-1"
                *ngIf="invoiceForm.get('buyerName')?.invalid && invoiceForm.get('buyerName')?.touched"
              >
                {{ '::Saudi:Zatca:BuyerNameRequired' | abpLocalization }}
              </div>
            </div>

            <div class="col-md-6">
              <label class="form-label">{{ '::Saudi:Zatca:BuyerVatNumber' | abpLocalization }}</label>
              <input type="text" class="form-control" formControlName="buyerVatNumber" />
            </div>
          </div>

          <!-- Invoice Lines -->
          <h6 class="mb-3 mt-4">{{ '::Saudi:Zatca:InvoiceLines' | abpLocalization }}</h6>
          <div class="table-responsive">
            <table class="table table-bordered">
              <thead class="table-light">
                <tr>
                  <th style="width: 30%">
                    {{ '::Saudi:Zatca:ItemName' | abpLocalization }}
                    <span class="text-danger">*</span>
                  </th>
                  <th style="width: 12%">
                    {{ '::Saudi:Zatca:Quantity' | abpLocalization }}
                    <span class="text-danger">*</span>
                  </th>
                  <th style="width: 15%">
                    {{ '::Saudi:Zatca:UnitPrice' | abpLocalization }}
                    <span class="text-danger">*</span>
                  </th>
                  <th style="width: 12%">
                    {{ '::Saudi:Zatca:TaxPercent' | abpLocalization }}
                    <span class="text-danger">*</span>
                  </th>
                  <th style="width: 15%">{{ '::Saudi:Zatca:TaxAmount' | abpLocalization }}</th>
                  <th style="width: 15%">{{ '::Saudi:Zatca:LineTotal' | abpLocalization }}</th>
                  <th style="width: 5%"></th>
                </tr>
              </thead>
              <tbody formArrayName="lines">
                <tr *ngFor="let line of lines.controls; let i = index" [formGroupName]="i">
                  <td>
                    <input type="text" class="form-control form-control-sm" formControlName="itemName" />
                  </td>
                  <td>
                    <input
                      type="number"
                      class="form-control form-control-sm"
                      formControlName="quantity"
                      min="0"
                      step="0.01"
                      (input)="calculateLineTotal(i)"
                    />
                  </td>
                  <td>
                    <input
                      type="number"
                      class="form-control form-control-sm"
                      formControlName="unitPrice"
                      min="0"
                      step="0.01"
                      (input)="calculateLineTotal(i)"
                    />
                  </td>
                  <td>
                    <input
                      type="number"
                      class="form-control form-control-sm"
                      formControlName="taxPercent"
                      min="0"
                      max="100"
                      step="0.01"
                      (input)="calculateLineTotal(i)"
                    />
                  </td>
                  <td>
                    <input
                      type="number"
                      class="form-control form-control-sm"
                      formControlName="taxAmount"
                      readonly
                    />
                  </td>
                  <td>
                    <input
                      type="number"
                      class="form-control form-control-sm"
                      formControlName="lineTotal"
                      readonly
                    />
                  </td>
                  <td class="text-center">
                    <button
                      type="button"
                      class="btn btn-sm btn-outline-danger"
                      (click)="removeLine(i)"
                      [disabled]="lines.length === 1"
                    >
                      <i class="bi bi-trash"></i>
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <button type="button" class="btn btn-sm btn-outline-primary mb-3" (click)="addLine()">
            <i class="bi bi-plus-circle"></i>
            {{ '::Saudi:Zatca:AddLine' | abpLocalization }}
          </button>

          <!-- Totals -->
          <div class="row">
            <div class="col-md-6 ms-auto">
              <div class="card bg-light">
                <div class="card-body">
                  <div class="row mb-2">
                    <div class="col-6 text-end">
                      <strong>{{ '::Saudi:Zatca:Subtotal' | abpLocalization }}:</strong>
                    </div>
                    <div class="col-6 text-end">{{ subtotal | number : '1.2-2' }} SAR</div>
                  </div>
                  <div class="row mb-2">
                    <div class="col-6 text-end">
                      <strong>{{ '::Saudi:Zatca:TotalTax' | abpLocalization }}:</strong>
                    </div>
                    <div class="col-6 text-end">{{ totalTax | number : '1.2-2' }} SAR</div>
                  </div>
                  <hr />
                  <div class="row">
                    <div class="col-6 text-end">
                      <strong class="fs-5">{{ '::Saudi:Zatca:GrandTotal' | abpLocalization }}:</strong>
                    </div>
                    <div class="col-6 text-end">
                      <strong class="fs-5">{{ grandTotal | number : '1.2-2' }} SAR</strong>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Action Buttons -->
          <div class="row mt-4">
            <div class="col">
              <button type="button" class="btn btn-secondary me-2" [routerLink]="['/saudi/zatca/invoices']">
                <i class="bi bi-x-circle"></i>
                {{ '::Saudi:Zatca:Cancel' | abpLocalization }}
              </button>
              <button type="submit" class="btn btn-primary" [disabled]="invoiceForm.invalid || isSubmitting">
                <i class="bi bi-check-circle"></i>
                {{ '::Saudi:Zatca:Save' | abpLocalization }}
                <span *ngIf="isSubmitting" class="spinner-border spinner-border-sm ms-2"></span>
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  `,
  styles: [],
})
export class InvoiceFormComponent implements OnInit {
  invoiceForm: FormGroup;
  sellers: ZatcaSellerDto[] = [];
  issueDate: Date | null = new Date();
  issueDateHijri: string | null = null;
  isEditMode = false;
  invoiceId: string | null = null;
  isSubmitting = false;
  loadingSellers = true;

  subtotal = 0;
  totalTax = 0;
  grandTotal = 0;

  typeOptions = [
    { value: ZatcaInvoiceType.Standard, label: 'Standard' },
    { value: ZatcaInvoiceType.Simplified, label: 'Simplified' },
    { value: ZatcaInvoiceType.StandardCreditNote, label: 'Credit' },
    { value: ZatcaInvoiceType.StandardDebitNote, label: 'Debit' },
  ];

  constructor(
    private fb: FormBuilder,
    private router: Router,
    private route: ActivatedRoute,
    private invoiceService: InvoiceService,
    private sellerService: SellerService
  ) {
    this.invoiceForm = this.fb.group({
      sellerId: ['', Validators.required],
      invoiceType: ['', Validators.required],
      issueDate: [new Date().toISOString().split('T')[0], Validators.required],
      issueDateHijri: [''],
      invoiceNumber: [''],
      buyerName: ['', Validators.required],
      buyerVatNumber: [''],
      currencyCode: ['SAR'],
      lines: this.fb.array([]),
    });
  }

  ngOnInit() {
    this.loadSellers();
    this.addLine();

    this.route.params.subscribe(params => {
      if (params['id']) {
        this.isEditMode = true;
        this.invoiceId = params['id'];
        this.loadInvoice(this.invoiceId!);
      }
    });
  }

  get lines(): FormArray {
    return this.invoiceForm.get('lines') as FormArray;
  }

  loadSellers() {
    this.loadingSellers = true;
    this.sellerService
      .getList({ skipCount: 0, maxResultCount: 100 })
      .pipe(finalize(() => (this.loadingSellers = false)))
      .subscribe(result => {
        this.sellers = result.items;
      });
  }

  loadInvoice(id: string) {
    this.invoiceService.get(id).subscribe(invoice => {
      this.invoiceForm.patchValue({
        sellerId: invoice.sellerId,
        invoiceType: invoice.invoiceType,
        issueDate: invoice.issueDate,
        issueDateHijri: invoice.issueDateHijri || '',
        invoiceNumber: invoice.invoiceNumber,
        buyerName: invoice.buyerName || '',
        buyerVatNumber: invoice.buyerVatNumber || '',
        currencyCode: invoice.currencyCode,
      });

      // Clear existing lines and add from invoice
      while (this.lines.length) {
        this.lines.removeAt(0);
      }
      invoice.lines.forEach((line, i) => {
        const lineGroup = this.fb.group({
          itemName: [line.itemName, Validators.required],
          quantity: [line.quantity, [Validators.required, Validators.min(0.01)]],
          unitPrice: [line.unitPrice, [Validators.required, Validators.min(0)]],
          taxPercent: [line.taxPercent, [Validators.required, Validators.min(0), Validators.max(100)]],
          taxAmount: [{ value: line.vatAmount, disabled: true }],
          lineTotal: [{ value: line.totalAmount, disabled: true }],
        });
        this.lines.push(lineGroup);
      });
      this.calculateTotals();
    });
  }

  onIssueDateChange(dual: DualDate) {
    this.issueDate = dual.gregorian;
    this.issueDateHijri = dual.hijriFormatted;
    this.invoiceForm.patchValue({
      issueDate: dual.gregorian?.toISOString().split('T')[0] || '',
      issueDateHijri: dual.hijriFormatted || '',
    });
  }

  addLine() {
    const lineGroup = this.fb.group({
      itemName: ['', Validators.required],
      quantity: [1, [Validators.required, Validators.min(0.01)]],
      unitPrice: [0, [Validators.required, Validators.min(0)]],
      taxPercent: [15, [Validators.required, Validators.min(0), Validators.max(100)]],
      taxAmount: [{ value: 0, disabled: true }],
      lineTotal: [{ value: 0, disabled: true }],
    });

    this.lines.push(lineGroup);
    this.calculateLineTotal(this.lines.length - 1);
  }

  removeLine(index: number) {
    if (this.lines.length > 1) {
      this.lines.removeAt(index);
      this.calculateTotals();
    }
  }

  calculateLineTotal(index: number) {
    const line = this.lines.at(index);
    const quantity = line.get('quantity')?.value || 0;
    const unitPrice = line.get('unitPrice')?.value || 0;
    const taxPercent = line.get('taxPercent')?.value || 0;

    const subtotal = quantity * unitPrice;
    const taxAmount = (subtotal * taxPercent) / 100;
    const lineTotal = subtotal + taxAmount;

    line.patchValue({
      taxAmount: taxAmount,
      lineTotal: lineTotal,
    });

    this.calculateTotals();
  }

  calculateTotals() {
    this.subtotal = 0;
    this.totalTax = 0;

    this.lines.controls.forEach(line => {
      const quantity = line.get('quantity')?.value || 0;
      const unitPrice = line.get('unitPrice')?.value || 0;
      const taxAmount = line.get('taxAmount')?.value || 0;

      this.subtotal += quantity * unitPrice;
      this.totalTax += taxAmount;
    });

    this.grandTotal = this.subtotal + this.totalTax;
  }

  onSubmit() {
    if (this.invoiceForm.invalid) {
      Object.keys(this.invoiceForm.controls).forEach(key => {
        this.invoiceForm.get(key)?.markAsTouched();
      });
      return;
    }

    this.isSubmitting = true;

    const formValue = this.invoiceForm.value;
    const dto = {
      sellerId: formValue.sellerId,
      invoiceNumber: formValue.invoiceNumber,
      invoiceType: Number(formValue.invoiceType),
      issueDate: formValue.issueDate,
      issueDateHijri: formValue.issueDateHijri || undefined,
      buyerName: formValue.buyerName || undefined,
      buyerVatNumber: formValue.buyerVatNumber || undefined,
      currencyCode: formValue.currencyCode || 'SAR',
      lines: this.lines.controls.map(line => ({
        itemName: line.get('itemName')?.value,
        quantity: line.get('quantity')?.value,
        unitPrice: line.get('unitPrice')?.value,
        taxPercent: line.get('taxPercent')?.value,
        taxCategoryCode: 'S',
      })),
    };

    const request$ = this.isEditMode && this.invoiceId
      ? this.invoiceService.update(this.invoiceId, dto)
      : this.invoiceService.create(dto);

    request$
      .pipe(finalize(() => (this.isSubmitting = false)))
      .subscribe({
        next: () => {
          this.router.navigate(['/saudi/zatca/invoices']);
        },
      });
  }
}
